# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'quicreator.ui'
#
# Created by: PyQt5 UI code generator 5.12
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_QUICreator(object):
    def setupUi(self, QUICreator):
        QUICreator.setObjectName("QUICreator")
        QUICreator.setEnabled(True)
        QUICreator.resize(1500, 800)
        self.centralwidget = QtWidgets.QWidget(QUICreator)
        self.centralwidget.setObjectName("centralwidget")
        self.horizontalLayout_9 = QtWidgets.QHBoxLayout(self.centralwidget)
        self.horizontalLayout_9.setObjectName("horizontalLayout_9")
        self.objFile = QtWidgets.QOpenGLWidget(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.objFile.sizePolicy().hasHeightForWidth())
        self.objFile.setSizePolicy(sizePolicy)
        self.objFile.setMinimumSize(QtCore.QSize(700, 700))
        self.objFile.setMaximumSize(QtCore.QSize(16777215, 16777215))
        self.objFile.setObjectName("objFile")
        self.horizontalLayout_9.addWidget(self.objFile)
        self.tabWidget = QtWidgets.QTabWidget(self.centralwidget)
        self.tabWidget.setEnabled(True)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.tabWidget.sizePolicy().hasHeightForWidth())
        self.tabWidget.setSizePolicy(sizePolicy)
        self.tabWidget.setMinimumSize(QtCore.QSize(760, 700))
        self.tabWidget.setMaximumSize(QtCore.QSize(16777215, 16777215))
        self.tabWidget.setObjectName("tabWidget")
        self.importTab = QtWidgets.QWidget()
        self.importTab.setObjectName("importTab")
        self.verticalLayout_5 = QtWidgets.QVBoxLayout(self.importTab)
        self.verticalLayout_5.setContentsMargins(3, 3, 3, 3)
        self.verticalLayout_5.setObjectName("verticalLayout_5")
        self.gridLayout_4 = QtWidgets.QGridLayout()
        self.gridLayout_4.setObjectName("gridLayout_4")
        self.groupBox_8 = QtWidgets.QGroupBox(self.importTab)
        self.groupBox_8.setObjectName("groupBox_8")
        self.gridLayout_9 = QtWidgets.QGridLayout(self.groupBox_8)
        self.gridLayout_9.setObjectName("gridLayout_9")
        self.data_pic_4 = QtWidgets.QLabel(self.groupBox_8)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.data_pic_4.sizePolicy().hasHeightForWidth())
        self.data_pic_4.setSizePolicy(sizePolicy)
        self.data_pic_4.setMinimumSize(QtCore.QSize(320, 240))
        self.data_pic_4.setText("")
        self.data_pic_4.setObjectName("data_pic_4")
        self.gridLayout_9.addWidget(self.data_pic_4, 2, 1, 1, 1)
        self.data_pic_3 = QtWidgets.QLabel(self.groupBox_8)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.data_pic_3.sizePolicy().hasHeightForWidth())
        self.data_pic_3.setSizePolicy(sizePolicy)
        self.data_pic_3.setMinimumSize(QtCore.QSize(320, 240))
        self.data_pic_3.setText("")
        self.data_pic_3.setObjectName("data_pic_3")
        self.gridLayout_9.addWidget(self.data_pic_3, 2, 0, 1, 1)
        self.data_pic_2 = QtWidgets.QLabel(self.groupBox_8)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.data_pic_2.sizePolicy().hasHeightForWidth())
        self.data_pic_2.setSizePolicy(sizePolicy)
        self.data_pic_2.setMinimumSize(QtCore.QSize(320, 240))
        self.data_pic_2.setText("")
        self.data_pic_2.setObjectName("data_pic_2")
        self.gridLayout_9.addWidget(self.data_pic_2, 1, 1, 1, 1)
        self.data_pic_1 = QtWidgets.QLabel(self.groupBox_8)
        self.data_pic_1.setEnabled(True)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.data_pic_1.sizePolicy().hasHeightForWidth())
        self.data_pic_1.setSizePolicy(sizePolicy)
        self.data_pic_1.setMinimumSize(QtCore.QSize(320, 240))
        self.data_pic_1.setText("")
        self.data_pic_1.setObjectName("data_pic_1")
        self.gridLayout_9.addWidget(self.data_pic_1, 1, 0, 1, 1)
        self.training_report = QtWidgets.QPlainTextEdit(self.groupBox_8)
        self.training_report.setReadOnly(True)
        self.training_report.setObjectName("training_report")
        self.gridLayout_9.addWidget(self.training_report, 0, 0, 1, 2)
        self.gridLayout_4.addWidget(self.groupBox_8, 2, 0, 1, 3)
        self.training = QtWidgets.QPushButton(self.importTab)
        self.training.setCheckable(False)
        self.training.setObjectName("training")
        self.gridLayout_4.addWidget(self.training, 1, 2, 1, 1)
        self.importStatus = QtWidgets.QLabel(self.importTab)
        self.importStatus.setText("")
        self.importStatus.setObjectName("importStatus")
        self.gridLayout_4.addWidget(self.importStatus, 1, 1, 1, 1)
        self.importFile = QtWidgets.QPushButton(self.importTab)
        self.importFile.setCheckable(False)
        self.importFile.setObjectName("importFile")
        self.gridLayout_4.addWidget(self.importFile, 0, 2, 1, 1)
        self.label_2 = QtWidgets.QLabel(self.importTab)
        self.label_2.setText("")
        self.label_2.setObjectName("label_2")
        self.gridLayout_4.addWidget(self.label_2, 1, 0, 1, 1)
        self.label = QtWidgets.QLabel(self.importTab)
        self.label.setAlignment(QtCore.Qt.AlignCenter)
        self.label.setObjectName("label")
        self.gridLayout_4.addWidget(self.label, 0, 0, 1, 1)
        self.path = QtWidgets.QLineEdit(self.importTab)
        self.path.setReadOnly(True)
        self.path.setObjectName("path")
        self.gridLayout_4.addWidget(self.path, 0, 1, 1, 1)
        self.verticalLayout_5.addLayout(self.gridLayout_4)
        self.tabWidget.addTab(self.importTab, "")
        self.predictTab = QtWidgets.QWidget()
        self.predictTab.setObjectName("predictTab")
        self.gridLayout_2 = QtWidgets.QGridLayout(self.predictTab)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.groupBox_9 = QtWidgets.QGroupBox(self.predictTab)
        self.groupBox_9.setObjectName("groupBox_9")
        self.gridLayout_11 = QtWidgets.QGridLayout(self.groupBox_9)
        self.gridLayout_11.setObjectName("gridLayout_11")
        self.prediction = QtWidgets.QPushButton(self.groupBox_9)
        self.prediction.setObjectName("prediction")
        self.gridLayout_11.addWidget(self.prediction, 2, 2, 1, 1)
        self.prediction_table = QtWidgets.QTableWidget(self.groupBox_9)
        self.prediction_table.setObjectName("prediction_table")
        self.prediction_table.setColumnCount(0)
        self.prediction_table.setRowCount(0)
        self.gridLayout_11.addWidget(self.prediction_table, 2, 1, 1, 1)
        self.label_29 = QtWidgets.QLabel(self.groupBox_9)
        self.label_29.setObjectName("label_29")
        self.gridLayout_11.addWidget(self.label_29, 2, 0, 1, 1)
        self.filepath2_2 = QtWidgets.QLineEdit(self.groupBox_9)
        self.filepath2_2.setReadOnly(True)
        self.filepath2_2.setObjectName("filepath2_2")
        self.gridLayout_11.addWidget(self.filepath2_2, 0, 1, 1, 1)
        self.label_28 = QtWidgets.QLabel(self.groupBox_9)
        self.label_28.setObjectName("label_28")
        self.gridLayout_11.addWidget(self.label_28, 0, 0, 1, 1)
        self.button2_2 = QtWidgets.QPushButton(self.groupBox_9)
        self.button2_2.setObjectName("button2_2")
        self.gridLayout_11.addWidget(self.button2_2, 0, 2, 1, 1)
        self.groupBox_10 = QtWidgets.QGroupBox(self.groupBox_9)
        self.groupBox_10.setObjectName("groupBox_10")
        self.gridLayout_12 = QtWidgets.QGridLayout(self.groupBox_10)
        self.gridLayout_12.setObjectName("gridLayout_12")
        self.pre_pic_1 = QtWidgets.QLabel(self.groupBox_10)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pre_pic_1.sizePolicy().hasHeightForWidth())
        self.pre_pic_1.setSizePolicy(sizePolicy)
        self.pre_pic_1.setMinimumSize(QtCore.QSize(320, 240))
        self.pre_pic_1.setText("")
        self.pre_pic_1.setObjectName("pre_pic_1")
        self.gridLayout_12.addWidget(self.pre_pic_1, 0, 0, 1, 1)
        self.pre_pic_2 = QtWidgets.QLabel(self.groupBox_10)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pre_pic_2.sizePolicy().hasHeightForWidth())
        self.pre_pic_2.setSizePolicy(sizePolicy)
        self.pre_pic_2.setMinimumSize(QtCore.QSize(320, 240))
        self.pre_pic_2.setText("")
        self.pre_pic_2.setObjectName("pre_pic_2")
        self.gridLayout_12.addWidget(self.pre_pic_2, 0, 1, 1, 1)
        self.gridLayout_11.addWidget(self.groupBox_10, 1, 0, 1, 3)
        self.gridLayout_2.addWidget(self.groupBox_9, 1, 0, 1, 1)
        self.groupBox = QtWidgets.QGroupBox(self.predictTab)
        self.groupBox.setObjectName("groupBox")
        self.gridLayout_10 = QtWidgets.QGridLayout(self.groupBox)
        self.gridLayout_10.setObjectName("gridLayout_10")
        self.filepath2_1 = QtWidgets.QLineEdit(self.groupBox)
        self.filepath2_1.setReadOnly(True)
        self.filepath2_1.setObjectName("filepath2_1")
        self.gridLayout_10.addWidget(self.filepath2_1, 0, 1, 1, 1)
        self.label_27 = QtWidgets.QLabel(self.groupBox)
        self.label_27.setObjectName("label_27")
        self.gridLayout_10.addWidget(self.label_27, 0, 0, 1, 1)
        self.button2_1 = QtWidgets.QPushButton(self.groupBox)
        self.button2_1.setObjectName("button2_1")
        self.gridLayout_10.addWidget(self.button2_1, 0, 2, 1, 1)
        self.update3d = QtWidgets.QPushButton(self.groupBox)
        self.update3d.setObjectName("update3d")
        self.gridLayout_10.addWidget(self.update3d, 1, 2, 1, 1)
        self.gridLayout_2.addWidget(self.groupBox, 0, 0, 1, 1)
        self.tabWidget.addTab(self.predictTab, "")
        self.datatableTab = QtWidgets.QWidget()
        self.datatableTab.setObjectName("datatableTab")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.datatableTab)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.tableWidget = QtWidgets.QTableWidget(self.datatableTab)
        self.tableWidget.setObjectName("tableWidget")
        self.tableWidget.setColumnCount(0)
        self.tableWidget.setRowCount(0)
        self.horizontalLayout.addWidget(self.tableWidget)
        self.tabWidget.addTab(self.datatableTab, "")
        self.reportTab = QtWidgets.QWidget()
        self.reportTab.setObjectName("reportTab")
        self.horizontalLayout_5 = QtWidgets.QHBoxLayout(self.reportTab)
        self.horizontalLayout_5.setObjectName("horizontalLayout_5")
        self.tabWidget_2 = QtWidgets.QTabWidget(self.reportTab)
        self.tabWidget_2.setTabPosition(QtWidgets.QTabWidget.South)
        self.tabWidget_2.setObjectName("tabWidget_2")
        self.cover = QtWidgets.QWidget()
        self.cover.setObjectName("cover")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout(self.cover)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.groupBox_2 = QtWidgets.QGroupBox(self.cover)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.groupBox_2.sizePolicy().hasHeightForWidth())
        self.groupBox_2.setSizePolicy(sizePolicy)
        self.groupBox_2.setTitle("")
        self.groupBox_2.setCheckable(True)
        self.groupBox_2.setObjectName("groupBox_2")
        self.gridLayout_6 = QtWidgets.QGridLayout(self.groupBox_2)
        self.gridLayout_6.setObjectName("gridLayout_6")
        self.doc_type = QtWidgets.QLineEdit(self.groupBox_2)
        self.doc_type.setClearButtonEnabled(True)
        self.doc_type.setObjectName("doc_type")
        self.gridLayout_6.addWidget(self.doc_type, 5, 3, 1, 1)
        self.label_17 = QtWidgets.QLabel(self.groupBox_2)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_17.sizePolicy().hasHeightForWidth())
        self.label_17.setSizePolicy(sizePolicy)
        self.label_17.setObjectName("label_17")
        self.gridLayout_6.addWidget(self.label_17, 2, 1, 1, 1)
        self.label_20 = QtWidgets.QLabel(self.groupBox_2)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_20.sizePolicy().hasHeightForWidth())
        self.label_20.setSizePolicy(sizePolicy)
        self.label_20.setObjectName("label_20")
        self.gridLayout_6.addWidget(self.label_20, 9, 1, 1, 1)
        self.doc_company = QtWidgets.QLineEdit(self.groupBox_2)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.doc_company.sizePolicy().hasHeightForWidth())
        self.doc_company.setSizePolicy(sizePolicy)
        self.doc_company.setClearButtonEnabled(True)
        self.doc_company.setObjectName("doc_company")
        self.gridLayout_6.addWidget(self.doc_company, 3, 3, 1, 1)
        self.label_15 = QtWidgets.QLabel(self.groupBox_2)
        self.label_15.setObjectName("label_15")
        self.gridLayout_6.addWidget(self.label_15, 3, 1, 1, 1)
        self.label_3 = QtWidgets.QLabel(self.groupBox_2)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_3.sizePolicy().hasHeightForWidth())
        self.label_3.setSizePolicy(sizePolicy)
        self.label_3.setObjectName("label_3")
        self.gridLayout_6.addWidget(self.label_3, 1, 1, 1, 1)
        self.label_32 = QtWidgets.QLabel(self.groupBox_2)
        self.label_32.setObjectName("label_32")
        self.gridLayout_6.addWidget(self.label_32, 6, 1, 1, 1)
        self.doc_code = QtWidgets.QLineEdit(self.groupBox_2)
        self.doc_code.setReadOnly(False)
        self.doc_code.setClearButtonEnabled(True)
        self.doc_code.setObjectName("doc_code")
        self.gridLayout_6.addWidget(self.doc_code, 4, 3, 1, 1)
        self.doc_content4 = QtWidgets.QLineEdit(self.groupBox_2)
        self.doc_content4.setClearButtonEnabled(True)
        self.doc_content4.setObjectName("doc_content4")
        self.gridLayout_6.addWidget(self.doc_content4, 13, 3, 1, 1)
        self.label_33 = QtWidgets.QLabel(self.groupBox_2)
        self.label_33.setObjectName("label_33")
        self.gridLayout_6.addWidget(self.label_33, 7, 1, 1, 1)
        self.label_31 = QtWidgets.QLabel(self.groupBox_2)
        self.label_31.setObjectName("label_31")
        self.gridLayout_6.addWidget(self.label_31, 4, 1, 1, 1)
        self.doc_reporter = QtWidgets.QLineEdit(self.groupBox_2)
        self.doc_reporter.setReadOnly(False)
        self.doc_reporter.setClearButtonEnabled(True)
        self.doc_reporter.setObjectName("doc_reporter")
        self.gridLayout_6.addWidget(self.doc_reporter, 6, 3, 1, 1)
        self.doc_date = QtWidgets.QLineEdit(self.groupBox_2)
        self.doc_date.setReadOnly(False)
        self.doc_date.setClearButtonEnabled(True)
        self.doc_date.setObjectName("doc_date")
        self.gridLayout_6.addWidget(self.doc_date, 7, 3, 1, 1)
        self.doc_content1 = QtWidgets.QLineEdit(self.groupBox_2)
        self.doc_content1.setClearButtonEnabled(True)
        self.doc_content1.setObjectName("doc_content1")
        self.gridLayout_6.addWidget(self.doc_content1, 10, 3, 1, 1)
        self.doc_content3 = QtWidgets.QLineEdit(self.groupBox_2)
        self.doc_content3.setClearButtonEnabled(True)
        self.doc_content3.setObjectName("doc_content3")
        self.gridLayout_6.addWidget(self.doc_content3, 12, 3, 1, 1)
        self.doc_content2 = QtWidgets.QLineEdit(self.groupBox_2)
        self.doc_content2.setClearButtonEnabled(True)
        self.doc_content2.setObjectName("doc_content2")
        self.gridLayout_6.addWidget(self.doc_content2, 11, 3, 1, 1)
        self.doc_4 = QtWidgets.QCheckBox(self.groupBox_2)
        self.doc_4.setChecked(True)
        self.doc_4.setObjectName("doc_4")
        self.gridLayout_6.addWidget(self.doc_4, 13, 1, 1, 1)
        self.doc_3 = QtWidgets.QCheckBox(self.groupBox_2)
        self.doc_3.setChecked(True)
        self.doc_3.setObjectName("doc_3")
        self.gridLayout_6.addWidget(self.doc_3, 12, 1, 1, 1)
        self.doc_1 = QtWidgets.QCheckBox(self.groupBox_2)
        self.doc_1.setChecked(True)
        self.doc_1.setObjectName("doc_1")
        self.gridLayout_6.addWidget(self.doc_1, 10, 1, 1, 1)
        self.doc_status = QtWidgets.QLabel(self.groupBox_2)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.doc_status.sizePolicy().hasHeightForWidth())
        self.doc_status.setSizePolicy(sizePolicy)
        self.doc_status.setText("")
        self.doc_status.setWordWrap(True)
        self.doc_status.setObjectName("doc_status")
        self.gridLayout_6.addWidget(self.doc_status, 17, 1, 1, 1)
        self.doc_2 = QtWidgets.QCheckBox(self.groupBox_2)
        self.doc_2.setChecked(True)
        self.doc_2.setObjectName("doc_2")
        self.gridLayout_6.addWidget(self.doc_2, 11, 1, 1, 1)
        self.label_34 = QtWidgets.QLabel(self.groupBox_2)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_34.sizePolicy().hasHeightForWidth())
        self.label_34.setSizePolicy(sizePolicy)
        self.label_34.setText("")
        self.label_34.setObjectName("label_34")
        self.gridLayout_6.addWidget(self.label_34, 8, 1, 1, 1)
        self.label_19 = QtWidgets.QLabel(self.groupBox_2)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_19.sizePolicy().hasHeightForWidth())
        self.label_19.setSizePolicy(sizePolicy)
        self.label_19.setObjectName("label_19")
        self.gridLayout_6.addWidget(self.label_19, 5, 1, 1, 1)
        self.label_21 = QtWidgets.QLabel(self.groupBox_2)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_21.sizePolicy().hasHeightForWidth())
        self.label_21.setSizePolicy(sizePolicy)
        self.label_21.setWordWrap(True)
        self.label_21.setObjectName("label_21")
        self.gridLayout_6.addWidget(self.label_21, 14, 1, 1, 1)
        self.doc_path_button = QtWidgets.QPushButton(self.groupBox_2)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.doc_path_button.sizePolicy().hasHeightForWidth())
        self.doc_path_button.setSizePolicy(sizePolicy)
        self.doc_path_button.setCheckable(True)
        self.doc_path_button.setObjectName("doc_path_button")
        self.gridLayout_6.addWidget(self.doc_path_button, 16, 1, 1, 1)
        self.label_18 = QtWidgets.QLabel(self.groupBox_2)
        self.label_18.setObjectName("label_18")
        self.gridLayout_6.addWidget(self.label_18, 15, 1, 1, 1)
        self.doc_filename = QtWidgets.QLineEdit(self.groupBox_2)
        self.doc_filename.setClearButtonEnabled(True)
        self.doc_filename.setObjectName("doc_filename")
        self.gridLayout_6.addWidget(self.doc_filename, 15, 3, 1, 1)
        self.doc_path = QtWidgets.QLineEdit(self.groupBox_2)
        self.doc_path.setReadOnly(True)
        self.doc_path.setClearButtonEnabled(True)
        self.doc_path.setObjectName("doc_path")
        self.gridLayout_6.addWidget(self.doc_path, 16, 3, 1, 1)
        self.doc_heading = QtWidgets.QLineEdit(self.groupBox_2)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.doc_heading.sizePolicy().hasHeightForWidth())
        self.doc_heading.setSizePolicy(sizePolicy)
        self.doc_heading.setClearButtonEnabled(True)
        self.doc_heading.setObjectName("doc_heading")
        self.gridLayout_6.addWidget(self.doc_heading, 2, 3, 1, 1)
        self.groupBox_7 = QtWidgets.QGroupBox(self.groupBox_2)
        self.groupBox_7.setAutoFillBackground(False)
        self.groupBox_7.setTitle("")
        self.groupBox_7.setFlat(False)
        self.groupBox_7.setObjectName("groupBox_7")
        self.horizontalLayout_6 = QtWidgets.QHBoxLayout(self.groupBox_7)
        self.horizontalLayout_6.setObjectName("horizontalLayout_6")
        self.doc_clear = QtWidgets.QPushButton(self.groupBox_7)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.doc_clear.sizePolicy().hasHeightForWidth())
        self.doc_clear.setSizePolicy(sizePolicy)
        self.doc_clear.setCheckable(True)
        self.doc_clear.setChecked(False)
        self.doc_clear.setObjectName("doc_clear")
        self.horizontalLayout_6.addWidget(self.doc_clear)
        self.doc_source = QtWidgets.QPushButton(self.groupBox_7)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.doc_source.sizePolicy().hasHeightForWidth())
        self.doc_source.setSizePolicy(sizePolicy)
        self.doc_source.setLayoutDirection(QtCore.Qt.RightToLeft)
        self.doc_source.setAutoFillBackground(False)
        self.doc_source.setCheckable(True)
        self.doc_source.setObjectName("doc_source")
        self.horizontalLayout_6.addWidget(self.doc_source)
        self.gridLayout_6.addWidget(self.groupBox_7, 17, 3, 1, 1)
        self.verticalLayout_3.addWidget(self.groupBox_2)
        self.tabWidget_2.addTab(self.cover, "")
        self.text1 = QtWidgets.QWidget()
        self.text1.setObjectName("text1")
        self.verticalLayout_4 = QtWidgets.QVBoxLayout(self.text1)
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.doc_1_tableview = QtWidgets.QTableView(self.text1)
        self.doc_1_tableview.setObjectName("doc_1_tableview")
        self.doc_1_tableview.horizontalHeader().setVisible(False)
        self.doc_1_tableview.horizontalHeader().setCascadingSectionResizes(False)
        self.doc_1_tableview.horizontalHeader().setStretchLastSection(True)
        self.doc_1_tableview.verticalHeader().setCascadingSectionResizes(False)
        self.doc_1_tableview.verticalHeader().setStretchLastSection(True)
        self.verticalLayout_4.addWidget(self.doc_1_tableview)
        self.tabWidget_2.addTab(self.text1, "")
        self.text2 = QtWidgets.QWidget()
        self.text2.setObjectName("text2")
        self.gridLayout_8 = QtWidgets.QGridLayout(self.text2)
        self.gridLayout_8.setObjectName("gridLayout_8")
        self.groupBox_3 = QtWidgets.QGroupBox(self.text2)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.groupBox_3.sizePolicy().hasHeightForWidth())
        self.groupBox_3.setSizePolicy(sizePolicy)
        self.groupBox_3.setTitle("")
        self.groupBox_3.setObjectName("groupBox_3")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout(self.groupBox_3)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.doc_2_start = QtWidgets.QLineEdit(self.groupBox_3)
        self.doc_2_start.setClearButtonEnabled(True)
        self.doc_2_start.setObjectName("doc_2_start")
        self.horizontalLayout_2.addWidget(self.doc_2_start)
        self.label_23 = QtWidgets.QLabel(self.groupBox_3)
        self.label_23.setObjectName("label_23")
        self.horizontalLayout_2.addWidget(self.label_23)
        self.doc_2_end = QtWidgets.QLineEdit(self.groupBox_3)
        self.doc_2_end.setClearButtonEnabled(True)
        self.doc_2_end.setObjectName("doc_2_end")
        self.horizontalLayout_2.addWidget(self.doc_2_end)
        self.doc_2_status = QtWidgets.QLabel(self.groupBox_3)
        self.doc_2_status.setText("")
        self.doc_2_status.setWordWrap(True)
        self.doc_2_status.setObjectName("doc_2_status")
        self.horizontalLayout_2.addWidget(self.doc_2_status)
        self.doc_2_button1 = QtWidgets.QPushButton(self.groupBox_3)
        self.doc_2_button1.setCheckable(True)
        self.doc_2_button1.setObjectName("doc_2_button1")
        self.horizontalLayout_2.addWidget(self.doc_2_button1)
        self.gridLayout_8.addWidget(self.groupBox_3, 2, 1, 1, 1)
        self.groupBox_4 = QtWidgets.QGroupBox(self.text2)
        self.groupBox_4.setTitle("")
        self.groupBox_4.setObjectName("groupBox_4")
        self.verticalLayout_7 = QtWidgets.QVBoxLayout(self.groupBox_4)
        self.verticalLayout_7.setObjectName("verticalLayout_7")
        self.doc_2_button2 = QtWidgets.QPushButton(self.groupBox_4)
        self.doc_2_button2.setCheckable(True)
        self.doc_2_button2.setObjectName("doc_2_button2")
        self.verticalLayout_7.addWidget(self.doc_2_button2)
        self.doc_2_button3 = QtWidgets.QPushButton(self.groupBox_4)
        self.doc_2_button3.setCheckable(True)
        self.doc_2_button3.setObjectName("doc_2_button3")
        self.verticalLayout_7.addWidget(self.doc_2_button3)
        self.gridLayout_8.addWidget(self.groupBox_4, 3, 0, 1, 1)
        self.doc_2_tablename = QtWidgets.QLineEdit(self.text2)
        self.doc_2_tablename.setClearButtonEnabled(True)
        self.doc_2_tablename.setObjectName("doc_2_tablename")
        self.gridLayout_8.addWidget(self.doc_2_tablename, 0, 1, 1, 1)
        self.label_24 = QtWidgets.QLabel(self.text2)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_24.sizePolicy().hasHeightForWidth())
        self.label_24.setSizePolicy(sizePolicy)
        self.label_24.setObjectName("label_24")
        self.gridLayout_8.addWidget(self.label_24, 2, 0, 1, 1)
        self.label_22 = QtWidgets.QLabel(self.text2)
        self.label_22.setObjectName("label_22")
        self.gridLayout_8.addWidget(self.label_22, 0, 0, 1, 1)
        self.doc_2_table = QtWidgets.QTableWidget(self.text2)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.doc_2_table.sizePolicy().hasHeightForWidth())
        self.doc_2_table.setSizePolicy(sizePolicy)
        self.doc_2_table.setObjectName("doc_2_table")
        self.doc_2_table.setColumnCount(0)
        self.doc_2_table.setRowCount(0)
        self.gridLayout_8.addWidget(self.doc_2_table, 3, 1, 1, 1)
        self.label_25 = QtWidgets.QLabel(self.text2)
        self.label_25.setObjectName("label_25")
        self.gridLayout_8.addWidget(self.label_25, 4, 0, 1, 1)
        self.doc_2_text = QtWidgets.QPlainTextEdit(self.text2)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.doc_2_text.sizePolicy().hasHeightForWidth())
        self.doc_2_text.setSizePolicy(sizePolicy)
        self.doc_2_text.setObjectName("doc_2_text")
        self.gridLayout_8.addWidget(self.doc_2_text, 4, 1, 1, 1)
        self.tabWidget_2.addTab(self.text2, "")
        self.text3 = QtWidgets.QWidget()
        self.text3.setObjectName("text3")
        self.gridLayout_7 = QtWidgets.QGridLayout(self.text3)
        self.gridLayout_7.setObjectName("gridLayout_7")
        self.groupBox_6 = QtWidgets.QGroupBox(self.text3)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.groupBox_6.sizePolicy().hasHeightForWidth())
        self.groupBox_6.setSizePolicy(sizePolicy)
        self.groupBox_6.setTitle("")
        self.groupBox_6.setObjectName("groupBox_6")
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout(self.groupBox_6)
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.doc_3_pic1 = QtWidgets.QLabel(self.groupBox_6)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.doc_3_pic1.sizePolicy().hasHeightForWidth())
        self.doc_3_pic1.setSizePolicy(sizePolicy)
        self.doc_3_pic1.setMinimumSize(QtCore.QSize(200, 200))
        self.doc_3_pic1.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.doc_3_pic1.setText("")
        self.doc_3_pic1.setObjectName("doc_3_pic1")
        self.horizontalLayout_3.addWidget(self.doc_3_pic1)
        self.doc_3_pic2 = QtWidgets.QLabel(self.groupBox_6)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.doc_3_pic2.sizePolicy().hasHeightForWidth())
        self.doc_3_pic2.setSizePolicy(sizePolicy)
        self.doc_3_pic2.setMinimumSize(QtCore.QSize(200, 200))
        self.doc_3_pic2.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.doc_3_pic2.setFrameShadow(QtWidgets.QFrame.Plain)
        self.doc_3_pic2.setText("")
        self.doc_3_pic2.setObjectName("doc_3_pic2")
        self.horizontalLayout_3.addWidget(self.doc_3_pic2)
        self.gridLayout_7.addWidget(self.groupBox_6, 0, 1, 1, 1)
        self.doc_3_picname2 = QtWidgets.QLineEdit(self.text3)
        self.doc_3_picname2.setReadOnly(False)
        self.doc_3_picname2.setClearButtonEnabled(True)
        self.doc_3_picname2.setObjectName("doc_3_picname2")
        self.gridLayout_7.addWidget(self.doc_3_picname2, 2, 1, 1, 1)
        self.label_26 = QtWidgets.QLabel(self.text3)
        self.label_26.setObjectName("label_26")
        self.gridLayout_7.addWidget(self.label_26, 3, 0, 1, 1)
        self.doc_3_picname1 = QtWidgets.QLineEdit(self.text3)
        self.doc_3_picname1.setReadOnly(False)
        self.doc_3_picname1.setClearButtonEnabled(True)
        self.doc_3_picname1.setObjectName("doc_3_picname1")
        self.gridLayout_7.addWidget(self.doc_3_picname1, 1, 1, 1, 1)
        self.doc_3_button2 = QtWidgets.QPushButton(self.text3)
        self.doc_3_button2.setObjectName("doc_3_button2")
        self.gridLayout_7.addWidget(self.doc_3_button2, 2, 0, 1, 1)
        self.doc_3_text = QtWidgets.QPlainTextEdit(self.text3)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.doc_3_text.sizePolicy().hasHeightForWidth())
        self.doc_3_text.setSizePolicy(sizePolicy)
        self.doc_3_text.setObjectName("doc_3_text")
        self.gridLayout_7.addWidget(self.doc_3_text, 3, 1, 1, 1)
        self.doc_3_button1 = QtWidgets.QPushButton(self.text3)
        self.doc_3_button1.setObjectName("doc_3_button1")
        self.gridLayout_7.addWidget(self.doc_3_button1, 1, 0, 1, 1)
        self.doc_3_status = QtWidgets.QLabel(self.text3)
        self.doc_3_status.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.doc_3_status.setObjectName("doc_3_status")
        self.gridLayout_7.addWidget(self.doc_3_status, 0, 0, 1, 1)
        self.tabWidget_2.addTab(self.text3, "")
        self.text4 = QtWidgets.QWidget()
        self.text4.setObjectName("text4")
        self.verticalLayout_12 = QtWidgets.QVBoxLayout(self.text4)
        self.verticalLayout_12.setObjectName("verticalLayout_12")
        self.groupBox_5 = QtWidgets.QGroupBox(self.text4)
        self.groupBox_5.setTitle("")
        self.groupBox_5.setCheckable(True)
        self.groupBox_5.setObjectName("groupBox_5")
        self.gridLayout_13 = QtWidgets.QGridLayout(self.groupBox_5)
        self.gridLayout_13.setObjectName("gridLayout_13")
        self.label_48 = QtWidgets.QLabel(self.groupBox_5)
        self.label_48.setObjectName("label_48")
        self.gridLayout_13.addWidget(self.label_48, 1, 0, 1, 1)
        self.doc_4_text = QtWidgets.QPlainTextEdit(self.groupBox_5)
        self.doc_4_text.setObjectName("doc_4_text")
        self.gridLayout_13.addWidget(self.doc_4_text, 1, 1, 1, 1)
        self.verticalLayout_12.addWidget(self.groupBox_5)
        self.tabWidget_2.addTab(self.text4, "")
        self.horizontalLayout_5.addWidget(self.tabWidget_2)
        self.tabWidget.addTab(self.reportTab, "")
        self.emailTab = QtWidgets.QWidget()
        self.emailTab.setObjectName("emailTab")
        self.verticalLayout_6 = QtWidgets.QVBoxLayout(self.emailTab)
        self.verticalLayout_6.setObjectName("verticalLayout_6")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout()
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.MailgroupBox = QtWidgets.QGroupBox(self.emailTab)
        self.MailgroupBox.setFlat(False)
        self.MailgroupBox.setCheckable(True)
        self.MailgroupBox.setChecked(True)
        self.MailgroupBox.setObjectName("MailgroupBox")
        self.gridLayout = QtWidgets.QGridLayout(self.MailgroupBox)
        self.gridLayout.setObjectName("gridLayout")
        self.MailContext = QtWidgets.QPlainTextEdit(self.MailgroupBox)
        self.MailContext.setOverwriteMode(False)
        self.MailContext.setObjectName("MailContext")
        self.gridLayout.addWidget(self.MailContext, 4, 0, 1, 3)
        self.attachment = QtWidgets.QTreeView(self.MailgroupBox)
        self.attachment.setObjectName("attachment")
        self.gridLayout.addWidget(self.attachment, 3, 0, 1, 3)
        self.receiver = QtWidgets.QTreeWidget(self.MailgroupBox)
        self.receiver.setObjectName("receiver")
        self.receiver.headerItem().setText(0, "1")
        self.gridLayout.addWidget(self.receiver, 1, 0, 1, 3)
        self.maillabel = QtWidgets.QLabel(self.MailgroupBox)
        self.maillabel.setWordWrap(True)
        self.maillabel.setObjectName("maillabel")
        self.gridLayout.addWidget(self.maillabel, 5, 0, 1, 1)
        self.sendemail = QtWidgets.QPushButton(self.MailgroupBox)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.sendemail.sizePolicy().hasHeightForWidth())
        self.sendemail.setSizePolicy(sizePolicy)
        self.sendemail.setCheckable(True)
        self.sendemail.setObjectName("sendemail")
        self.gridLayout.addWidget(self.sendemail, 5, 2, 1, 1)
        self.clearemail = QtWidgets.QPushButton(self.MailgroupBox)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.clearemail.sizePolicy().hasHeightForWidth())
        self.clearemail.setSizePolicy(sizePolicy)
        self.clearemail.setCheckable(True)
        self.clearemail.setChecked(False)
        self.clearemail.setObjectName("clearemail")
        self.gridLayout.addWidget(self.clearemail, 5, 1, 1, 1)
        self.clearflie = QtWidgets.QPushButton(self.MailgroupBox)
        self.clearflie.setIconSize(QtCore.QSize(16, 16))
        self.clearflie.setCheckable(True)
        self.clearflie.setObjectName("clearflie")
        self.gridLayout.addWidget(self.clearflie, 2, 2, 1, 1)
        self.head = QtWidgets.QLineEdit(self.MailgroupBox)
        self.head.setClearButtonEnabled(True)
        self.head.setObjectName("head")
        self.gridLayout.addWidget(self.head, 0, 0, 1, 3)
        self.File = QtWidgets.QLineEdit(self.MailgroupBox)
        self.File.setReadOnly(True)
        self.File.setObjectName("File")
        self.gridLayout.addWidget(self.File, 2, 0, 1, 2)
        self.verticalLayout_2.addWidget(self.MailgroupBox)
        self.verticalLayout_6.addLayout(self.verticalLayout_2)
        self.tabWidget.addTab(self.emailTab, "")
        self.settingTab = QtWidgets.QWidget()
        self.settingTab.setObjectName("settingTab")
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout(self.settingTab)
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.horizontalLayout_7 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_7.setObjectName("horizontalLayout_7")
        self.emailsetting = QtWidgets.QGroupBox(self.settingTab)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.emailsetting.sizePolicy().hasHeightForWidth())
        self.emailsetting.setSizePolicy(sizePolicy)
        self.emailsetting.setCheckable(False)
        self.emailsetting.setObjectName("emailsetting")
        self.gridLayout_3 = QtWidgets.QGridLayout(self.emailsetting)
        self.gridLayout_3.setObjectName("gridLayout_3")
        self.label_10 = QtWidgets.QLabel(self.emailsetting)
        self.label_10.setText("")
        self.label_10.setObjectName("label_10")
        self.gridLayout_3.addWidget(self.label_10, 7, 1, 1, 1)
        self.label_5 = QtWidgets.QLabel(self.emailsetting)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_5.sizePolicy().hasHeightForWidth())
        self.label_5.setSizePolicy(sizePolicy)
        self.label_5.setObjectName("label_5")
        self.gridLayout_3.addWidget(self.label_5, 0, 0, 1, 1)
        self.label_6 = QtWidgets.QLabel(self.emailsetting)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_6.sizePolicy().hasHeightForWidth())
        self.label_6.setSizePolicy(sizePolicy)
        self.label_6.setObjectName("label_6")
        self.gridLayout_3.addWidget(self.label_6, 1, 0, 1, 1)
        self.emailsender = QtWidgets.QLineEdit(self.emailsetting)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.emailsender.sizePolicy().hasHeightForWidth())
        self.emailsender.setSizePolicy(sizePolicy)
        self.emailsender.setClearButtonEnabled(True)
        self.emailsender.setObjectName("emailsender")
        self.gridLayout_3.addWidget(self.emailsender, 2, 1, 1, 1)
        self.label_7 = QtWidgets.QLabel(self.emailsetting)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_7.sizePolicy().hasHeightForWidth())
        self.label_7.setSizePolicy(sizePolicy)
        self.label_7.setObjectName("label_7")
        self.gridLayout_3.addWidget(self.label_7, 2, 0, 1, 1)
        self.port = QtWidgets.QLineEdit(self.emailsetting)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.port.sizePolicy().hasHeightForWidth())
        self.port.setSizePolicy(sizePolicy)
        self.port.setClearButtonEnabled(True)
        self.port.setObjectName("port")
        self.gridLayout_3.addWidget(self.port, 1, 1, 1, 1)
        self.label_8 = QtWidgets.QLabel(self.emailsetting)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_8.sizePolicy().hasHeightForWidth())
        self.label_8.setSizePolicy(sizePolicy)
        self.label_8.setObjectName("label_8")
        self.gridLayout_3.addWidget(self.label_8, 3, 0, 1, 1)
        self.smtpserver = QtWidgets.QLineEdit(self.emailsetting)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.smtpserver.sizePolicy().hasHeightForWidth())
        self.smtpserver.setSizePolicy(sizePolicy)
        self.smtpserver.setClearButtonEnabled(True)
        self.smtpserver.setObjectName("smtpserver")
        self.gridLayout_3.addWidget(self.smtpserver, 0, 1, 1, 1)
        self.emailsource = QtWidgets.QPushButton(self.emailsetting)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.emailsource.sizePolicy().hasHeightForWidth())
        self.emailsource.setSizePolicy(sizePolicy)
        self.emailsource.setCheckable(True)
        self.emailsource.setObjectName("emailsource")
        self.gridLayout_3.addWidget(self.emailsource, 4, 1, 1, 1)
        self.emailpwd = QtWidgets.QLineEdit(self.emailsetting)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.emailpwd.sizePolicy().hasHeightForWidth())
        self.emailpwd.setSizePolicy(sizePolicy)
        self.emailpwd.setEchoMode(QtWidgets.QLineEdit.Password)
        self.emailpwd.setCursorMoveStyle(QtCore.Qt.LogicalMoveStyle)
        self.emailpwd.setClearButtonEnabled(True)
        self.emailpwd.setObjectName("emailpwd")
        self.gridLayout_3.addWidget(self.emailpwd, 3, 1, 1, 1)
        self.emailstatus = QtWidgets.QLabel(self.emailsetting)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.emailstatus.sizePolicy().hasHeightForWidth())
        self.emailstatus.setSizePolicy(sizePolicy)
        self.emailstatus.setText("")
        self.emailstatus.setObjectName("emailstatus")
        self.gridLayout_3.addWidget(self.emailstatus, 6, 1, 1, 1)
        self.label_9 = QtWidgets.QLabel(self.emailsetting)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_9.sizePolicy().hasHeightForWidth())
        self.label_9.setSizePolicy(sizePolicy)
        self.label_9.setText("")
        self.label_9.setObjectName("label_9")
        self.gridLayout_3.addWidget(self.label_9, 5, 1, 1, 1)
        self.horizontalLayout_7.addWidget(self.emailsetting)
        self.accountsetting = QtWidgets.QGroupBox(self.settingTab)
        self.accountsetting.setEnabled(True)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.accountsetting.sizePolicy().hasHeightForWidth())
        self.accountsetting.setSizePolicy(sizePolicy)
        self.accountsetting.setCheckable(False)
        self.accountsetting.setObjectName("accountsetting")
        self.gridLayout_5 = QtWidgets.QGridLayout(self.accountsetting)
        self.gridLayout_5.setObjectName("gridLayout_5")
        self.label_13 = QtWidgets.QLabel(self.accountsetting)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_13.sizePolicy().hasHeightForWidth())
        self.label_13.setSizePolicy(sizePolicy)
        self.label_13.setObjectName("label_13")
        self.gridLayout_5.addWidget(self.label_13, 2, 0, 1, 1)
        self.accountstatus = QtWidgets.QLabel(self.accountsetting)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.accountstatus.sizePolicy().hasHeightForWidth())
        self.accountstatus.setSizePolicy(sizePolicy)
        self.accountstatus.setText("")
        self.accountstatus.setObjectName("accountstatus")
        self.gridLayout_5.addWidget(self.accountstatus, 5, 1, 1, 1)
        self.label_11 = QtWidgets.QLabel(self.accountsetting)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_11.sizePolicy().hasHeightForWidth())
        self.label_11.setSizePolicy(sizePolicy)
        self.label_11.setObjectName("label_11")
        self.gridLayout_5.addWidget(self.label_11, 1, 0, 1, 1)
        self.label_14 = QtWidgets.QLabel(self.accountsetting)
        self.label_14.setObjectName("label_14")
        self.gridLayout_5.addWidget(self.label_14, 3, 0, 1, 1)
        self.oldpwd = QtWidgets.QLineEdit(self.accountsetting)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.oldpwd.sizePolicy().hasHeightForWidth())
        self.oldpwd.setSizePolicy(sizePolicy)
        self.oldpwd.setMinimumSize(QtCore.QSize(158, 0))
        self.oldpwd.setEchoMode(QtWidgets.QLineEdit.Password)
        self.oldpwd.setClearButtonEnabled(True)
        self.oldpwd.setObjectName("oldpwd")
        self.gridLayout_5.addWidget(self.oldpwd, 1, 1, 1, 1)
        self.newpwd1 = QtWidgets.QLineEdit(self.accountsetting)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.newpwd1.sizePolicy().hasHeightForWidth())
        self.newpwd1.setSizePolicy(sizePolicy)
        self.newpwd1.setEchoMode(QtWidgets.QLineEdit.Password)
        self.newpwd1.setClearButtonEnabled(True)
        self.newpwd1.setObjectName("newpwd1")
        self.gridLayout_5.addWidget(self.newpwd1, 2, 1, 1, 1)
        self.newpwd2 = QtWidgets.QLineEdit(self.accountsetting)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.newpwd2.sizePolicy().hasHeightForWidth())
        self.newpwd2.setSizePolicy(sizePolicy)
        self.newpwd2.setEchoMode(QtWidgets.QLineEdit.Password)
        self.newpwd2.setObjectName("newpwd2")
        self.gridLayout_5.addWidget(self.newpwd2, 3, 1, 1, 1)
        self.accountsource = QtWidgets.QPushButton(self.accountsetting)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.accountsource.sizePolicy().hasHeightForWidth())
        self.accountsource.setSizePolicy(sizePolicy)
        self.accountsource.setCheckable(True)
        self.accountsource.setObjectName("accountsource")
        self.gridLayout_5.addWidget(self.accountsource, 4, 1, 1, 1)
        self.label_16 = QtWidgets.QLabel(self.accountsetting)
        self.label_16.setText("")
        self.label_16.setObjectName("label_16")
        self.gridLayout_5.addWidget(self.label_16, 6, 1, 1, 1)
        self.label_12 = QtWidgets.QLabel(self.accountsetting)
        self.label_12.setEnabled(True)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_12.sizePolicy().hasHeightForWidth())
        self.label_12.setSizePolicy(sizePolicy)
        self.label_12.setMinimumSize(QtCore.QSize(158, 21))
        self.label_12.setObjectName("label_12")
        self.gridLayout_5.addWidget(self.label_12, 0, 0, 1, 1)
        self.horizontalLayout_7.addWidget(self.accountsetting)
        self.horizontalLayout_4.addLayout(self.horizontalLayout_7)
        self.tabWidget.addTab(self.settingTab, "")
        self.horizontalLayout_9.addWidget(self.tabWidget)
        QUICreator.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(QUICreator)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 1500, 22))
        self.menubar.setObjectName("menubar")
        self.menu_A = QtWidgets.QMenu(self.menubar)
        self.menu_A.setObjectName("menu_A")
        self.menu_B = QtWidgets.QMenu(self.menubar)
        self.menu_B.setObjectName("menu_B")
        self.menu_C = QtWidgets.QMenu(self.menubar)
        self.menu_C.setObjectName("menu_C")
        QUICreator.setMenuBar(self.menubar)
        self.action_about = QtWidgets.QAction(QUICreator)
        self.action_about.setObjectName("action_about")
        self.action_refresh = QtWidgets.QAction(QUICreator)
        self.action_refresh.setObjectName("action_refresh")
        self.action_changeuser = QtWidgets.QAction(QUICreator)
        self.action_changeuser.setObjectName("action_changeuser")
        self.action_quit = QtWidgets.QAction(QUICreator)
        self.action_quit.setObjectName("action_quit")
        self.action_X = QtWidgets.QAction(QUICreator)
        self.action_X.setObjectName("action_X")
        self.action_C_2 = QtWidgets.QAction(QUICreator)
        self.action_C_2.setObjectName("action_C_2")
        self.action_V = QtWidgets.QAction(QUICreator)
        self.action_V.setObjectName("action_V")
        self.actionGouj = QtWidgets.QAction(QUICreator)
        self.actionGouj.setObjectName("actionGouj")
        self.action_light = QtWidgets.QAction(QUICreator)
        self.action_light.setObjectName("action_light")
        self.action_dark = QtWidgets.QAction(QUICreator)
        self.action_dark.setObjectName("action_dark")
        self.actionshengcheng = QtWidgets.QAction(QUICreator)
        self.actionshengcheng.setObjectName("actionshengcheng")
        self.actiond = QtWidgets.QAction(QUICreator)
        self.actiond.setObjectName("actiond")
        self.menu_A.addAction(self.action_about)
        self.menu_A.addAction(self.action_refresh)
        self.menu_A.addSeparator()
        self.menu_A.addAction(self.action_changeuser)
        self.menu_A.addAction(self.action_quit)
        self.menu_B.addAction(self.action_X)
        self.menu_B.addAction(self.action_C_2)
        self.menu_B.addAction(self.action_V)
        self.menu_C.addAction(self.action_light)
        self.menu_C.addAction(self.action_dark)
        self.menubar.addAction(self.menu_A.menuAction())
        self.menubar.addAction(self.menu_B.menuAction())
        self.menubar.addAction(self.menu_C.menuAction())

        self.retranslateUi(QUICreator)
        self.tabWidget.setCurrentIndex(1)
        self.tabWidget_2.setCurrentIndex(4)
        QtCore.QMetaObject.connectSlotsByName(QUICreator)

    def retranslateUi(self, QUICreator):
        _translate = QtCore.QCoreApplication.translate
        QUICreator.setWindowTitle(_translate("QUICreator", "MainWindow"))
        self.groupBox_8.setTitle(_translate("QUICreator", "数据分析"))
        self.training.setText(_translate("QUICreator", "导入并训练"))
        self.importFile.setText(_translate("QUICreator", "选择文件"))
        self.label.setText(_translate("QUICreator", "导入光谱数据: "))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.importTab), _translate("QUICreator", "导入光谱与训练"))
        self.groupBox_9.setTitle(_translate("QUICreator", " 预测矿岩类别"))
        self.prediction.setText(_translate("QUICreator", "开始预测"))
        self.label_29.setText(_translate("QUICreator", "预测结果: "))
        self.label_28.setText(_translate("QUICreator", "导入光谱数据: "))
        self.button2_2.setText(_translate("QUICreator", "选择文件"))
        self.groupBox_10.setTitle(_translate("QUICreator", "预测分析"))
        self.groupBox.setTitle(_translate("QUICreator", "导入点云数据并生成建模"))
        self.label_27.setText(_translate("QUICreator", "导入点云数据: "))
        self.button2_1.setText(_translate("QUICreator", "选择文件"))
        self.update3d.setText(_translate("QUICreator", "更新建模 "))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.predictTab), _translate("QUICreator", "导入点云与预测"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.datatableTab), _translate("QUICreator", "查看数据"))
        self.label_17.setText(_translate("QUICreator", "报告标题*:"))
        self.label_20.setText(_translate("QUICreator", "目录:"))
        self.label_15.setText(_translate("QUICreator", "使用单位*:"))
        self.label_3.setText(_translate("QUICreator", "封皮:"))
        self.label_32.setText(_translate("QUICreator", "报告人*:"))
        self.doc_content4.setText(_translate("QUICreator", "总结"))
        self.label_33.setText(_translate("QUICreator", "报告日期*:"))
        self.label_31.setText(_translate("QUICreator", "报告编号*:"))
        self.doc_content1.setText(_translate("QUICreator", "资料审查报告"))
        self.doc_content3.setText(_translate("QUICreator", "数据分析"))
        self.doc_content2.setText(_translate("QUICreator", "数据图表"))
        self.doc_4.setText(_translate("QUICreator", "报告内容4  "))
        self.doc_3.setText(_translate("QUICreator", "报告内容3  "))
        self.doc_1.setText(_translate("QUICreator", "报告内容1  "))
        self.doc_2.setText(_translate("QUICreator", "报告内容2  "))
        self.label_19.setText(_translate("QUICreator", "报告类型*:"))
        self.label_21.setText(_translate("QUICreator", "Note:请先完成所选部分"))
        self.doc_path_button.setText(_translate("QUICreator", "选择路径*:"))
        self.label_18.setText(_translate("QUICreator", "文件重命名*:"))
        self.doc_clear.setText(_translate("QUICreator", "refresh/clear"))
        self.doc_source.setText(_translate("QUICreator", "生成报告"))
        self.tabWidget_2.setTabText(self.tabWidget_2.indexOf(self.cover), _translate("QUICreator", "封皮与目录"))
        self.tabWidget_2.setTabText(self.tabWidget_2.indexOf(self.text1), _translate("QUICreator", "1.资料审查报告"))
        self.doc_2_start.setText(_translate("QUICreator", "请输入行数"))
        self.label_23.setText(_translate("QUICreator", "to"))
        self.doc_2_end.setText(_translate("QUICreator", "请输入行数"))
        self.doc_2_button1.setText(_translate("QUICreator", "选择"))
        self.doc_2_button2.setText(_translate("QUICreator", "全选"))
        self.doc_2_button3.setText(_translate("QUICreator", "全不选"))
        self.label_24.setText(_translate("QUICreator", "选择数据:"))
        self.label_22.setText(_translate("QUICreator", "表格命名:"))
        self.label_25.setText(_translate("QUICreator", "正文:"))
        self.tabWidget_2.setTabText(self.tabWidget_2.indexOf(self.text2), _translate("QUICreator", "2.数据表格"))
        self.doc_3_picname2.setText(_translate("QUICreator", "图片命名"))
        self.label_26.setText(_translate("QUICreator", "正文:"))
        self.doc_3_picname1.setText(_translate("QUICreator", "图片命名"))
        self.doc_3_button2.setText(_translate("QUICreator", "选择图片"))
        self.doc_3_button1.setText(_translate("QUICreator", "选择图片"))
        self.doc_3_status.setText(_translate("QUICreator", "预览:"))
        self.tabWidget_2.setTabText(self.tabWidget_2.indexOf(self.text3), _translate("QUICreator", "3.数据分析"))
        self.label_48.setText(_translate("QUICreator", "总结:"))
        self.tabWidget_2.setTabText(self.tabWidget_2.indexOf(self.text4), _translate("QUICreator", "4.总结"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.reportTab), _translate("QUICreator", "生成报表"))
        self.MailgroupBox.setTitle(_translate("QUICreator", "SendReport"))
        self.maillabel.setText(_translate("QUICreator", "发送状态: "))
        self.sendemail.setText(_translate("QUICreator", "Send"))
        self.clearemail.setText(_translate("QUICreator", "Clear"))
        self.clearflie.setText(_translate("QUICreator", "Clear"))
        self.head.setText(_translate("QUICreator", "请输入标题"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.emailTab), _translate("QUICreator", "发送报表"))
        self.emailsetting.setTitle(_translate("QUICreator", "邮件设置"))
        self.label_5.setText(_translate("QUICreator", "SMTP-Server: "))
        self.label_6.setText(_translate("QUICreator", "Port:"))
        self.label_7.setText(_translate("QUICreator", "Sender:"))
        self.label_8.setText(_translate("QUICreator", "Password:"))
        self.emailsource.setText(_translate("QUICreator", "Source"))
        self.accountsetting.setTitle(_translate("QUICreator", "账户设置"))
        self.label_13.setText(_translate("QUICreator", "输入新密码:"))
        self.label_11.setText(_translate("QUICreator", "输入原始密码:"))
        self.label_14.setText(_translate("QUICreator", "再次输入新密码:"))
        self.accountsource.setText(_translate("QUICreator", "Source"))
        self.label_12.setText(_translate("QUICreator", "修改密码:"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.settingTab), _translate("QUICreator", "设置"))
        self.menu_A.setTitle(_translate("QUICreator", "Mining System"))
        self.menu_B.setTitle(_translate("QUICreator", "编辑(&E)"))
        self.menu_C.setTitle(_translate("QUICreator", "设置"))
        self.action_about.setText(_translate("QUICreator", "关于Mining System"))
        self.action_refresh.setText(_translate("QUICreator", "刷新"))
        self.action_changeuser.setText(_translate("QUICreator", "切换账号"))
        self.action_quit.setText(_translate("QUICreator", "退出系统"))
        self.action_X.setText(_translate("QUICreator", "剪切(&X) "))
        self.action_C_2.setText(_translate("QUICreator", "复制(&C)"))
        self.action_V.setText(_translate("QUICreator", "粘贴(&V)"))
        self.actionGouj.setText(_translate("QUICreator", "构建项目(&B)"))
        self.action_light.setText(_translate("QUICreator", "light model"))
        self.action_dark.setText(_translate("QUICreator", "dark model"))
        self.actionshengcheng.setText(_translate("QUICreator", "生成报表"))
        self.actiond.setText(_translate("QUICreator", "导入数据"))


